#!/bin/sh 

# Copyright (C) 2015 by Yuri Victorovich. All rights reserved.

# PROVIDE: vbox_to_tor
# REQUIRE: LOGIN ipfw
# KEYWORD: shutdown
# BEFORE: tor

# Add the following lines to /etc/rc.conf to enable vbox_to_tor:
# vbox_to_tor_enable (bool):	Set to "YES" to enable dhcp. Default: "NO"
# vbox_to_tor_ifaces (list):	Set it to the list of interfaces. Default: "tap0"
#                                 At least one interface is required.
# vbox_to_tor_net_pattern (str):Set it to the network pattern. Default: "172.16"
# vbox_to_tor_rule_base (uint):	Set it to the the rule number block location. Default: "3000"
# vbox_to_tor_extra_ports (list):	Set it to the the list of ports to open from host to VMs. Default: ""
# vbox_to_tor_control_socket (bool):	Set it to "YES" to allow host administration using ControlSocket. Default: "NO"
# vbox_to_tor_allow_cookie_auth (bool):	Set it to "YES" to allow cookie administration on ControlSocket. Default: "NO"
# vbox_to_tor_use_base (bool):	Set it to "YES" to use central tor daemon on host. Default: "NO"
#                                 By default individual tor instance is launched per interface.
#                                 Choosing "YES" requires less resources, but is marginally less secure.
#                                 It requires tor service to run, but it should start after vbox-to-tor.
# vbox_to_tor_hs (str):		Set it to the list of hidden services to route to VMs. Default: ""
#                                 List is 'newline' or '|' separarated.
#                                 Every element represents the hidden service in the format:
#                                   tapN /dir/to/hs/ oport iport
# vbox_to_tor_user (str):	Set it to the user name that vbox-to-tor uses. Should be the same that tor uses. Default: "_tor"
# vbox_to_tor_group (str):	Set it to the group name that vbox-to-tor uses. Should be the same that tor uses. Default: "_tor"
# vbox_to_tor_show_colors (bool):Choosing "NO" prevents service status output to have colors. Default: "YES"
# ## per-VM options
# vbox_to_tor_tapN_tor_options (str): Set it to newline-separated list of additional options to add to every VM. Default: ""
# vbox_to_tor_tapN_fw_allow_nfs (list): Set it to space-separated list of NFS servers VM is allowed to mount from. Default: ""
#

. /etc/rc.subr

name=vbox_to_tor
rcvar=vbox_to_tor_enable
start_cmd="vbox_to_tor_start"
stop_cmd="vbox_to_tor_stop"
status_cmd="vbox_to_tor_status"

# signature that will be placed into torrc to later be able to find our lines
torrc_signature="VBoxToTOR"
# where all tors data dirs are
tor_dir=/var/tmp/vbox-to-tor
tor_conf=/usr/local/etc/tor/torrc
# consts
NL=$'\n'
TAB=$'\t'
nfs_ports="111 1110 2049 4045" # 111=portmap 1110=nfsd-status/nfsd-keepalive 2049=nfsd 4045=lockd + mountd port will be added based on the actual value

load_rc_config ${name}

: ${vbox_to_tor_enable="NO"}
: ${vbox_to_tor_ifaces="tap0"}
: ${vbox_to_tor_net_pattern="172.16"}
: ${vbox_to_tor_rule_base="3000"}
: ${vbox_to_tor_extra_ports=""}
: ${vbox_to_tor_control_socket="NO"}
: ${vbox_to_tor_allow_cookie_auth="NO"}
: ${vbox_to_tor_use_base="NO"}
: ${vbox_to_tor_hs=""}
: ${vbox_to_tor_user="_tor"}
: ${vbox_to_tor_group="_tor"}
: ${vbox_to_tor_show_colors="YES"}

## internals

tm() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')]"
}

is_user_authorized() {
  [ $(id -u) = 0 -o $(id -un) = ${vbox_to_tor_user} ] || return 1
}

is_user_authorized_with_msg() {
  is_user_authorized || ! echo "Only root and ${vbox_to_tor_user} can $1" >&2 || return 1
}

is_tor_installed() {
  [ -x /usr/local/bin/tor ] || return 1
}

fail() {
  echo "${name}: $1" >&2
  exit 1
}

get_per_vm_option() {
  echo $(eval "echo \$vbox_to_tor_${1}_${2}")
}

unique_port_set() {
  echo $vbox_to_tor_extra_ports $vbox_to_tor_hs_all_ports | tr " ${TAB}" '\n' | sort | uniq
}

unique_port_set_for_iface() {
  # eliminate port 22 here, I would rather keep 22 as a separate line in ipfw section to keep it explicit
  eval "echo \$vbox_to_tor_extra_ports \$vbox_to_tor_hs_${1}_iports | tr \" \${TAB}\" '\\n' | sort | uniq | grep -v ^22\$"
}

calc_lst_size() {
  local elt cnt=0
  for elt in $1; do
    cnt=$((cnt+1))
  done
  echo $cnt
}

calc_max_nfs_hosts_needed() {
  local max=0
  for iface in ${vbox_to_tor_ifaces}; do
    local cnt=$(calc_lst_size "$(get_per_vm_option ${iface} fw_allow_nfs)")
    if [ $cnt -gt $max ]; then
      max=$cnt
    fi
  done
  echo $max
}

nfs_ports_count() {
  # +1 due to the mountd variable port
  echo $(($(calc_lst_size "$nfs_ports")+1))
}

nfs_mountd_actual_port() {
  local port=$(rpcinfo -p | grep " mountd$" | awk '{print $4}' | uniq)
  if [ -z "$port" ]; then
    fail "can't determine mountd port: NFS requested but mountd isn't running?"
  fi
  echo $port
}

calc_rule_step() {
  # 6 base rules required per interface
  local cnt=6
  # add ports requested by the user
  cnt=$((cnt+$(calc_lst_size "$(unique_port_set)")))
  # add NFS ports if requested: tcp and udp per port
  cnt=$((cnt+2*$(nfs_ports_count)*$(calc_max_nfs_hosts_needed)))
  # pick the round number closest to needed
  for step in 10 20 50 100 200 500 1000; do
    if [ $cnt -le $step ]; then
      echo ${step}
      return
    fi
  done
  fail "too many ports requested"
}

check_tor_config() {
  # check we can really write /usr/local/etc/tor/torrc
  local rnd=$(jot -r 1 1000000 10000000)
  (test -w /usr/local/etc/tor/torrc &&
   test -w /usr/local/etc/tor &&
   touch /usr/local/etc/tor/torrc.tmp.${rnd} &&
   rm -f /usr/local/etc/tor/torrc.tmp.${rnd}) > /dev/null 2>/dev/null
}

ensure_kmod_loaded() {
  if !(kldstat -v | grep $1 >/dev/null); then
    kldload $1
  fi
}

parse_hs() {
  # parse HS definitions, if any
  local IFS="${NL}|"
  for hs in ${vbox_to_tor_hs}; do
    if [ -z "${hs}" ]; then
      continue
    fi
    local fidx=0
    local fld iface dir oport iport
    IFS=" ${TAB}"
    for fld in ${hs}; do
      case $fidx in
        0)
          iface="${fld}"
          ;;
        1)
          dir="${fld}"
          ;;
        2)
          oport="${fld}"
          ;;
        3)
          iport="${fld}"
          ;;
        *)
          echo "${name}: Too many fields in the hidden service definition: ${hs}" >&2
          return 1
          ;;
      esac
      fidx=$((fidx+1))
    done
    if [ -z "${iface}" -o -z "${dir}" -o -z "${oport}" -o -z "${iport}" ]; then
      echo "${name}: Too few fields in the hidden service definition: ${hs}" >&2
      return 1
    fi
    # fill hs info into global vars
    eval "vbox_to_tor_hs_${iface}=\"\$vbox_to_tor_hs_${iface} ${dir} ${oport} ${iport}\""
    eval "vbox_to_tor_hs_${iface}_iports=\"\$vbox_to_tor_hs_${iface}_iports ${iport}\""
    eval "vbox_to_tor_hs_all_iports=\"\$vbox_to_tor_hs_all_iports ${iport}\""
  done
}

create_tap() {
  for iface in ${vbox_to_tor_ifaces}; do
    local vm_id=$(echo $iface | sed -e 's/[a-z]*//')
    if !(ifconfig $iface create && \
         ifconfig $iface up && \
         ifconfig $iface inet "${vbox_to_tor_net_pattern}.${vm_id}.1/24" && \
         chown root:vboxusers /dev/$iface && \
         chmod 0660 /dev/$iface) >/dev/null 2>/dev/null; then
      echo "Failed to create interface $iface" >&2
      destroy_tap_silent
      return 1
    fi
  done
}

destroy_tap() {
  for iface in ${vbox_to_tor_ifaces}; do
    if ! ifconfig $iface destroy >/dev/null 2>/dev/null; then
      echo "Failed to destroy interface $iface" >&2
      destroy_tap_silent
      return 1
    fi
  done
}

destroy_tap_silent() {
  for iface in ${vbox_to_tor_ifaces}; do
    ifconfig $iface destroy >/dev/null 2>/dev/null
  done
}

change_sysctl() {
  # sysctl vars: VBox process needs to be able to open tapN, and listen on DNS port 53
  sysctl net.link.tap.user_open=1 >/dev/null &&
  sysctl net.inet.ip.portrange.reservedhigh=52 >/dev/null
}

add_ipfw_rules() {
  local ifaces="$1"
  local net_pattern="$2"
  local cmd=$vbox_to_tor_rule_base
  local step=$(calc_rule_step)
  local port
  local fwcmd="/sbin/ipfw -q"

  for iface in $ifaces; do
    local vm_id=$(echo $iface | sed -e 's/[a-z]*//')
    local vm_net="${net_pattern}.${vm_id}.0/24"
    local vm_gw="${net_pattern}.${vm_id}.1"

    # rule sub-index
    local pidx=0

    # NFS if requested (NFS should be befre the main section, because we override TCP here that normally goes to TOR)
    local nfs_hosts=$(get_per_vm_option "${iface}" "fw_allow_nfs")
    local nfs_host nfs_port
    for nfs_host in $nfs_hosts; do
      for nfs_port in $nfs_ports $(nfs_mountd_actual_port); do
        ${fwcmd} add $((cmd+pidx+0)) allow tcp from ${vm_net} to ${nfs_host} ${nfs_port} in via $iface keep-state
        ${fwcmd} add $((cmd+pidx+1)) allow udp from ${vm_net} to ${nfs_host} ${nfs_port} in via $iface keep-state
        pidx=$((pidx+2))
      done
    done

    # TCP: sink all TCP from this net to Tor's TransPort
    ${fwcmd} add $((cmd+pidx+0)) fwd ${vm_gw},9030 tcp from $vm_net to any in via $iface keep-state

    # DNS: allow DNS to go to TOR DNS port
    ${fwcmd} add $((cmd+pidx+1)) allow udp from ${vm_net} to ${vm_gw} 53 via $iface keep-state

    # DHCP: sink DHCP to server on gateway (DHCP requests can have both zero and non-zero source addresses)
    ${fwcmd} add $((cmd+pidx+3)) fwd ${vm_gw} udp from 0.0.0.0 to 255.255.255.255 67 in via $iface
    ${fwcmd} add $((cmd+pidx+2)) fwd ${vm_gw} udp from ${vm_net} to 255.255.255.255 67 in via $iface
    ${fwcmd} add $((cmd+pidx+4)) allow udp from ${vm_gw} to any 68 out via $iface

    # SSH: allow host-to-VM SSH for local administration
    ${fwcmd} add $((cmd+pidx+5)) allow tcp from ${vm_gw} to ${vm_net} 22 out via $iface keep-state

    pidx=$((pidx+6)) # 6 main rules

    # HS: you can add any additional host-to-VM TCP ports for TOR hidden services, or other purposes
    for port in $(unique_port_set_for_iface $iface); do
      ${fwcmd} add $((cmd+pidx)) allow tcp from ${vm_gw} to ${vm_net} ${port} out via $iface keep-state
      pidx=$((pidx+1))
    done

    # DENY: no other communication is allowed on this interface
    ${fwcmd} add $((cmd+step-1)) deny all from any to any via $iface

    # report
    echo "Added ipfw rules for VM ${iface} on ${vm_net} to connect to TOR"
    # move on
    cmd=$((cmd+step))
  done
}

start_tor_instance() {
  local iface="$1"
  local dir="$2"
  local gw="$3"
  local cl="$4"
  # create dirs
  (mkdir -p "${dir}/data" && chown -R ${vbox_to_tor_user}:${vbox_to_tor_group} "${dir}" && chmod -R 0700 "${dir}") ||
    ! echo "${name}: Failed to create ${dir}/data" || return 1
  # create blank torrc, because it isn't clear how to avoid using the default
  touch ${dir}/torrc && chown ${vbox_to_tor_user}:${vbox_to_tor_group} ${dir}/torrc && chmod 0600 ${dir}/torrc
  # prepare command line arguments
  local cmd="/usr/local/bin/tor"
  cmd="${cmd} -f ${dir}/torrc"
  cmd="${cmd} --PidFile ${dir}/tor.pid"
  cmd="${cmd} --RunAsDaemon 1"
  cmd="${cmd} --DataDirectory ${dir}/data"
  cmd="${cmd} --+Log \"notice file ${dir}/tor.log\""
  cmd="${cmd} --DNSPort 53"
  cmd="${cmd} --DNSListenAddress ${gw}"
  cmd="${cmd} --TransPort 9030"
  cmd="${cmd} --TransListenAddress ${gw}"
  cmd="${cmd} --SocksPort 0"
  if [ "${vbox_to_tor_control_socket}" = "YES" ]; then
    cmd="${cmd} --ControlSocket ${dir}/ctrl"
    cmd="${cmd} --CookieAuthentication 1"
  fi
  # add per-VM tor options
  IFS_OLD="$IFS"
  local IFS="${NL}"
  local opts=$(get_per_vm_option "${iface}" "tor_options") opt
  for opt in $opts; do
    opt=$(echo $opt | sed -e 's/^ *//g;s/ *$//g')
    if [ -n "${opt}" ]; then
      cmd="${cmd} --${opt}"
    fi
  done
  IFS="${IFS_OLD}"
  # enable hidden services resolution
  cmd="${cmd} --VirtualAddrNetworkIPv4 10.192.0.0/10"
  cmd="${cmd} --AutomapHostsOnResolve 1"
  # add hidden services that were requested
  local hidx=0
  local hs_fld hs_dir hs_oport hs_iport
  for hs_fld in $(eval "echo \$vbox_to_tor_hs_${iface}"); do
    case $hidx in
      0)
        hs_dir=${hs_fld}
        ;;
      1)
        hs_oport=${hs_fld}
        ;;
      2)
        hs_iport=${hs_fld}
        cmd="${cmd} --HiddenServiceDir ${hs_dir}"
        cmd="${cmd} --HiddenServicePort \"${hs_oport} ${cl}:${hs_iport}\""
        ;;
    esac
    [ $hidx -lt 2 ] && hidx=$((hidx+1)) || hidx=0
  done
  # log
  touch ${dir}/cmd.log && chown ${vbox_to_tor_user}:${vbox_to_tor_group} ${dir}/cmd.log && chmod 0600 ${dir}/cmd.log
  echo "$(tm) ----- Running VM (tunnel $iface) -----" >> ${dir}/cmd.log
  echo "CMD: ${cmd}" >> ${dir}/cmd.log
  echo "$(tm) ----- BEGIN OUTPUT (tunnel $iface) -----" >> ${dir}/cmd.log
  # run it
  su -m ${vbox_to_tor_user} -c "umask 0077; ${cmd}" >> ${dir}/cmd.log 2>&1
  echo "$(tm) ----- END OUTPUT (tunnel $iface) -----" >> ${dir}/cmd.log
  # check if it is running
  [ -r ${dir}/tor.pid -a -s ${dir}/tor.pid -a \
    "$(procstat $(cat ${dir}/tor.pid) | tail -1 | sed -E 's/^[[:space:]]*([0-9]+).*/\1/g' 2>/dev/null)" = "$(cat ${dir}/tor.pid)" ]
}

start_tor_instances() {
  (rm -rf ${tor_dir}; mkdir -p "${tor_dir}" && chown ${vbox_to_tor_user}:${vbox_to_tor_group} "${tor_dir}" && chmod 0700 "${tor_dir}") ||
    ! echo "${name}: Failed to create ${tor_dir}" || return 1
  for iface in ${vbox_to_tor_ifaces}; do
    local vm_id=$(echo $iface | sed -e 's/[a-z]*//')
    local vm_gw="${vbox_to_tor_net_pattern}.${vm_id}.1"
    local vm_cl="${vbox_to_tor_net_pattern}.${vm_id}.2"

    start_tor_instance "${iface}" "${tor_dir}/$iface" "${vm_gw}" "${vm_cl}" ||
      ! echo "${name}: Failed to start tor instance $iface" || stop_tor_instances_silent || return 1
  done
}

stop_tor_instances() {
  for iface in ${vbox_to_tor_ifaces}; do
    ([ -s ${tor_dir}/${iface}/tor.pid ] && kill $(cat ${tor_dir}/${iface}/tor.pid)) ||
       ! echo "${name}: failed to stop VM $iface" || stop_tor_instances_silent || return 1
    # XXX check the correctness of the above
  done
  rm -rf ${tor_dir}
}

stop_tor_instances_silent() {
  for iface in ${vbox_to_tor_ifaces}; do
    [ -s ${tor_dir}/${iface}/tor.pid ] && kill $(cat ${tor_dir}/${iface}/tor.pid) >/dev/null 2>/dev/null
  done
  # emergency stop, something went wrong, so keep logs
  return 0
}

start_tor() {
  (
    ([ ${vbox_to_tor_use_base} = "YES" ] && write_tor_config_section) ||
    ([ ${vbox_to_tor_use_base} = "NO" ] && start_tor_instances)
  ) || return 1
}

stop_tor() {
  (
    ([ ${vbox_to_tor_use_base} = "YES" ] && delete_tor_config_section) ||
    ([ ${vbox_to_tor_use_base} = "NO" ] && stop_tor_instances)
  ) || return 1
}

warn_to_restart_tor_if_running() {
  if [ -r /var/run/tor/tor.pid ] && procstat $(cat /var/run/tor/tor.pid) > /dev/null 2>/dev/null; then
    echo "WARNING vbox-to-tor changed tor configuration, you need to restart tor: 'service tor restart'"
  fi
}

write_tor_config_section() {
  # The "right" way of doing this is through Tor control port.
  # However, this requires authentication, and we don't have
  # the password. vbox-to-tor is an automated process, and has
  # to always succeed. So we just overwrite that file in the
  # old fashion way. We add our signature to every line, so
  # that we can always delete these lines when we are stopped.
  # See torproject ticket#15649 with the request for this
  # functionality

  local conf_tmp_old="${tor_conf}.vbox-to-tor.old.tmp"
  local conf_tmp_new="${tor_conf}.vbox-to-tor.new.tmp"

  rm -f $conf_tmp_new $conf_tmp_old &&
  (cat $tor_conf &&
   echo "# [$torrc_signature] BEGIN vbox-to-tor section" &&
   (for iface in ${vbox_to_tor_ifaces}; do
      local vm_id=$(echo $iface | sed -e 's/[a-z]*//')
      echo "DNSListenAddress   172.16.${vm_id}.1    # $torrc_signature"
      echo "TransListenAddress 172.16.${vm_id}.1    # $torrc_signature"
    done) &&
   echo "# [$torrc_signature] END vbox-to-tor section") > $conf_tmp_new
  if [ $? = 0 -a -f $conf_tmp_new ]; then
    mv $tor_conf $conf_tmp_old &&
    mv $conf_tmp_new $tor_conf &&
    rm -f $conf_tmp_old
    warn_to_restart_tor_if_running
  else
    return 1
  fi
}

delete_tor_config_section() {
  local conf_tmp_old="${tor_conf}.vbox-to-tor.old.tmp"
  local conf_tmp_new="${tor_conf}.vbox-to-tor.new.tmp"

  rm -f $conf_tmp_new $conf_tmp_old &&
  (cat $tor_conf | grep -v $torrc_signature) > $conf_tmp_new
  if [ $? = 0 -a -f $conf_tmp_new ]; then
    mv $tor_conf $conf_tmp_old &&
    mv $conf_tmp_new $tor_conf &&
    rm -f $conf_tmp_old
    warn_to_restart_tor_if_running
  else
    return 1
  fi
}

delete_ipfw_rules() {
  local ifaces="$1"
  local cmd=$vbox_to_tor_rule_base
  local step=$(calc_rule_step)
  local fwcmd="/sbin/ipfw -q"
  for iface in $ifaces; do
    ${fwcmd} delete $(jot - $cmd $((cmd+step-1))) 2>/dev/null
    cmd=$((cmd+step))
  done
}

guess_process_name() {
  local proc_vbox=$(procstat -c $1 | tail -1 | grep "VirtualBox")
  if [ -n "${proc_vbox}" ]; then
    echo $(echo ${proc_vbox} | sed -E "s/.*--comment (([^ ]| [^-]| -[^-])*)( --.*|[[:space:]]*)$/\1/g")
  fi
}

count_tunnels() {
  local cnt=0
  local iface
  for iface in ${vbox_to_tor_ifaces}; do
    cnt=$((cnt+1))
  done
  echo $cnt
}

print_hs_for_iface() {
  local iface="$1"
  local do_colors="$2"
  local hidx=0
  local hs_fld hs_dir hs_oport hs_iport
  local cnt=0
  for hs_fld in $(eval "echo \$vbox_to_tor_hs_${iface}"); do
    case $hidx in
      0)
        hs_dir=${hs_fld}
        ;;
      1)
        hs_oport=${hs_fld}
        ;;
      2)
        hs_iport=${hs_fld}
        # output: no newline in the end
        if [ $cnt -gt 0 ]; then
          echo ""
        fi
        local hs_name
        if [ -r "${hs_dir}/hostname" ]; then
          echo -n "      * hs: $(color_hs_name $(cat ${hs_dir}/hostname) ${do_colors}) (${hs_dir}) ${hs_oport} -> ${hs_iport}"
        else
          echo -n "      * hs: $(color_hs_name ${hs_dir} ${do_colors}) ${hs_oport} -> ${hs_iport}"
        fi
        cnt=$((cnt+1))
        ;;
    esac
    [ $hidx -lt 2 ] && hidx=$((hidx+1)) || hidx=0
  done
}

## internals: colors

RCol='\e[0m'    # Text Reset

# Regular           Bold                Underline           High Intensity      BoldHigh Intens     Background          High Intensity Backgrounds
Bla='\e[0;30m';     BBla='\e[1;30m';    UBla='\e[4;30m';    IBla='\e[0;90m';    BIBla='\e[1;90m';   On_Bla='\e[40m';    On_IBla='\e[0;100m';
Red='\e[0;31m';     BRed='\e[1;31m';    URed='\e[4;31m';    IRed='\e[0;91m';    BIRed='\e[1;91m';   On_Red='\e[41m';    On_IRed='\e[0;101m';
Gre='\e[0;32m';     BGre='\e[1;32m';    UGre='\e[4;32m';    IGre='\e[0;92m';    BIGre='\e[1;92m';   On_Gre='\e[42m';    On_IGre='\e[0;102m';
Yel='\e[0;33m';     BYel='\e[1;33m';    UYel='\e[4;33m';    IYel='\e[0;93m';    BIYel='\e[1;93m';   On_Yel='\e[43m';    On_IYel='\e[0;103m';
Blu='\e[0;34m';     BBlu='\e[1;34m';    UBlu='\e[4;34m';    IBlu='\e[0;94m';    BIBlu='\e[1;94m';   On_Blu='\e[44m';    On_IBlu='\e[0;104m';
Pur='\e[0;35m';     BPur='\e[1;35m';    UPur='\e[4;35m';    IPur='\e[0;95m';    BIPur='\e[1;95m';   On_Pur='\e[45m';    On_IPur='\e[0;105m';
Cya='\e[0;36m';     BCya='\e[1;36m';    UCya='\e[4;36m';    ICya='\e[0;96m';    BICya='\e[1;96m';   On_Cya='\e[46m';    On_ICya='\e[0;106m';
Whi='\e[0;37m';     BWhi='\e[1;37m';    UWhi='\e[4;37m';    IWhi='\e[0;97m';    BIWhi='\e[1;97m';   On_Whi='\e[47m';    On_IWhi='\e[0;107m';

color_os_name() {
  local os_name="$1"
  local do_colors="$2"
  if [ ${vbox_to_tor_show_colors} = "YES" -a ${do_colors} = 1 ]; then
    if expr "${os_name}" : "FreeBSD" > /dev/null; then
      echo -e "${Gre}${os_name}${RCol}"
    elif expr "${os_name}" : "Arch" > /dev/null; then
      echo -e "${Cya}${os_name}${RCol}"
    elif expr "${os_name}" : "Windows" > /dev/null; then
      echo -e "${Pur}${os_name}${RCol}"
    elif expr "${os_name}" : "Mint" > /dev/null; then
      echo -e "${Gre}${os_name}${RCol}"
    elif expr "${os_name}" : "Ubuntu" > /dev/null; then
      echo -e "${IRed}${os_name}${RCol}"
    elif expr "${os_name}" : "Fedora" > /dev/null; then
      echo -e "${IBlu}${os_name}${RCol}"
    else
      echo -e "${UBla}${os_name}${RCol}"
    fi
  else
    echo "${os_name}"
  fi
}

color_hs_name() {
  local hs_name="$1"
  local do_colors="$2"
  if [ ${vbox_to_tor_show_colors} = "YES" -a ${do_colors} = 1 ]; then
    echo -e "${URed}${hs_name}${RCol}"
  else
    echo "${hs_name}"
  fi
}

## interface: for service manager

vbox_to_tor_start() {
  # checks
  is_user_authorized_with_msg "start ${name}" || return 1
  [ ${vbox_to_tor_use_base} = "YES" ] || is_tor_installed || ! echo "Tor is not installed, $name can't start" || return 1
  # start
  (
    parse_hs &&
    check_tor_config &&
    ensure_kmod_loaded "if_tap" &&
    ensure_kmod_loaded "ipfw" &&
    create_tap &&
    add_ipfw_rules "${vbox_to_tor_ifaces}" "$vbox_to_tor_net_pattern" &&
    change_sysctl &&
    start_tor
  ) || return 1
}

vbox_to_tor_status() {
  parse_hs || return 1
  local cntOk=0
  local cntNo=0
  local msgOk msgNo strOpened
  local ntunnels=$(count_tunnels)
  local do_colors=0
  if [ -t 1 ]; then
    do_colors=1
  fi
  if [ $ntunnels -gt 1 ]; then
    local xnl="${NL}"
    local xbu=" * "
    local xlt=": "
    local xrt=""
  else
    local xnl=" "
    local xbu=""
    local xlt="("
    local xrt=")"
  fi
  for iface in ${vbox_to_tor_ifaces}; do
    if ! (ls /dev/ | grep $iface >/dev/null 2>/dev/null); then
      cntNo=$((cntNo+1))
      if [ $cntNo -gt 1 ]; then
        msgNo="${msgNo}"
      fi
      msgNo="${msgNo}${iface}"
    else
      cntOk=$((cntOk+1))
      local descr=""
      # vm pid
      strOpenedPid=$(ifconfig ${iface} | grep -i open | sed -e 's/[a-zA-Z[:space:]]*//g')
      if [ -n "${strOpenedPid}" ]; then
        descr="vm-pid=${strOpenedPid}"
        local processName=$(color_os_name "$(guess_process_name ${strOpenedPid})" ${do_colors})
        if [ -n "${processName}" ]; then
          descr="${descr} vm-name=${processName}"
        fi
      fi
      # tor pid
      if [ ${vbox_to_tor_use_base} = "NO" ]; then
        if [ -n "${descr}" ]; then
          descr="${descr} "
        fi
        descr="${descr}tor-pid=$(cat ${tor_dir}/${iface}/tor.pid 2>/dev/null || echo 'n/a')"
      fi
      # print iface status
      if [ $cntOk -gt 1 ]; then
        msgOk="${msgOk}${xnl}"
      fi
      if [ -n "${descr}" ]; then
        msgOk="${msgOk}${xbu}${iface}${xlt}${descr}${xrt}"
      else
        msgOk="${msgOk}${xbu}${iface}"
      fi
      local hs=$(print_hs_for_iface ${iface} ${do_colors})
      if [ -n "${hs}" ]; then
        msgOk="${msgOk}${NL}${hs}"
      fi
    fi
  done
  if [ $cntNo = 0 ]; then
    echo "$name is running with tunnels:${xnl}${msgOk}"
  elif [ $cntOk = 0 ]; then
    echo "$name is not running (${vbox_to_tor_ifaces})"
    return 1
  else
    echo "$name isn't properly setup: $cntNo of $((cntOk+cntNo)) tunnels doesn't exist (${vbox_to_tor_ifaces})"
    return 1
  fi
}

vbox_to_tor_stop() {
  is_user_authorized_with_msg "stop $name" || return 1
  (
    parse_hs &&
    delete_ipfw_rules "${vbox_to_tor_ifaces}" &&
    destroy_tap &&
    stop_tor
  ) || return 1
}

command="/usr/bin/true"

run_rc_command "$1"
